# Generated by Django 2.1.11 on 2019-08-11 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mineddata',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 12, 43, 51, 583529)),
        ),
    ]
