# Generated by Django 2.1.11 on 2019-08-11 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0002_auto_20190811_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelist',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 12, 45, 25, 462946)),
        ),
    ]
