# Generated by Django 2.1.11 on 2019-08-11 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0003_auto_20190811_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelist',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='sitelist',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 12, 46, 47, 146792)),
        ),
    ]
