# Generated by Django 2.1.11 on 2019-08-11 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0004_auto_20190811_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 13, 23, 51, 714596)),
        ),
        migrations.AlterField(
            model_name='sitelist',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitelist',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
