# Generated by Django 2.1.11 on 2019-08-11 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0005_auto_20190811_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 13, 25, 15, 469969)),
        ),
        migrations.AlterField(
            model_name='sitelist',
            name='scraped_status',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
